# Generated by Django 4.2.1 on 2023-09-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_couponapplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponapplied',
            name='coupon_name',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coupon'),
        ),
    ]
